### ISSUE TITLE
Question about sdd dataset.

### ISSUE THREAD

**Issue by daleigehhh** [HarshayuGirase/PECNet#67]
Hi, @ksachdeva, @karttikeya, @HarshayuGirase 

I am running the training code, but there is an error arised in the dataset code:
`Traceback (most recent call last):
  File "training_loop.py", line 139, in <module>
    train_dataset = SocialDataset(set_name="train", b_size=hyper_params["train_b_size"], t_tresh=hyper_params["time_thresh"], d_tresh=hyper_params["dist_thresh"], verbose=args.verbose)
  File "/home/yflei/TrajPre/PECNet/utils/social_utils.py", line 212, in __init__
    traj_new = np.array(traj_new)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (36,) + inhomogeneous part.`

I think it is because the inhomogenity of the length of the data in your pickle. Maybe the version of numpy I am using was different from yours.

**Comment by cao-jacky** [comment]
Hi,

It's been a long time since you posted this. But I was getting thrown a similar error when running the train cell of the `train_SDD_longterm.ipynb` notebook of `ynet`. I solved it by replacing the following L35 in `dataloader.py`

`return np.array(trajectories), meta, scene_list`

with this

`return np.array(trajectories, dtype=object), meta, scene_list`

I.e., specifying that the numpy array should be returned with an object dtype, and that solved my issue.
